import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-900 text-white'>
        <div className='container mx-auto w-3/5 min-h-screen flex flex-col justify-between'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
